# Generated by Django 5.2.1 on 2025-05-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_detection_model', models.CharField(choices=[('models_ai/detection/weapon.pt', 'weapon.pt (Fichier Présent)'), ('simulation', 'Simulation Détection')], default='simulation', help_text='Choisir le modèle de détection ou la simulation.', max_length=500, verbose_name='modèle de détection actif')),
                ('active_chatbot_model', models.CharField(choices=[('simulation', 'Simulation Chatbot')], default='simulation', help_text='Choisir le modèle de chatbot ou la simulation.', max_length=255, verbose_name='modèle de chatbot actif')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière modification le')),
            ],
            options={
                'verbose_name': "Paramètres de l'Application",
                'verbose_name_plural': "Paramètres de l'Application",
            },
        ),
    ]
