# Generated by Django 5.0.4 on 2025-05-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='dangerous_threshold',
            field=models.FloatField(default=0.5),
        ),
    ]
