# Generated by Django 5.0.4 on 2025-05-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appsettings_dangerous_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='dangerous_threshold',
            field=models.FloatField(default=0.5, help_text='Seuil de confiance minimum pour considérer une détection comme valide (0.1 à 1.0).', verbose_name='seuil de confiance'),
        ),
    ]
