# Generated by Django 5.0.4 on 2025-06-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appsettings_dangerous_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='active_chatbot_model',
            field=models.CharField(choices=[('grok-3', 'Grok-3 (xAI)'), ('simulation', 'Simulation Chatbot')], default='grok-3', help_text='Choisir le modèle de chatbot ou la simulation.', max_length=255, verbose_name='modèle de chatbot actif'),
        ),
    ]
