# Generated by Django 5.0.4 on 2025-06-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appsettings_active_chatbot_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='active_chatbot_model',
            field=models.CharField(choices=[('grok-3', 'Grok-3 (xAI)'), ('gemini-2.0-flash', 'gemini-2.0-flash (Google)'), ('simulation', 'Simulation Chatbot')], default='grok-3', help_text='Choisir le modèle de chatbot ou la simulation.', max_length=255, verbose_name='modèle de chatbot actif'),
        ),
    ]
