# Generated by Django 5.2.1 on 2025-05-25 18:25

import apps.detection.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DangerousCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Seules les catégories actives sont signalées.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'Catégorie Dangereuse',
                'verbose_name_plural': 'Catégories Dangereuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(help_text='Image ou vidéo analysée.', upload_to=apps.detection.models.detection_media_path, verbose_name='fichier uploadé')),
                ('detection_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='horodatage détection')),
                ('user_location', models.CharField(blank=True, help_text="Localisation de l'utilisateur au moment de la détection.", max_length=255, null=True, verbose_name='localisation utilisateur')),
                ('detected_objects', models.JSONField(blank=True, help_text='Résultats bruts du modèle IA (ex: [{"category": "knife", "confidence": 0.85, "bbox": [x,y,w,h]}]).', null=True, verbose_name='objets détectés')),
                ('contains_dangerous_category', models.BooleanField(default=False, help_text='Indique si une catégorie dangereuse active a été détectée (basé sur detected_objects).', verbose_name='contient catégorie dangereuse')),
                ('model_used', models.CharField(blank=True, help_text="Nom ou identifiant du modèle de détection utilisé (ou 'simulation').", max_length=255, null=True, verbose_name='modèle utilisé')),
                ('is_simulated', models.BooleanField(default=False, help_text="Indique si cette détection provient d'une simulation.", verbose_name='détection simulée')),
            ],
            options={
                'verbose_name': 'Journal de Détection',
                'verbose_name_plural': 'Journaux de Détection',
                'ordering': ['-detection_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ModelValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='horodatage validation')),
                ('is_correct', models.BooleanField(help_text='Le modèle (ou la simulation) a-t-il correctement identifié les objets ?', verbose_name='détection correcte?')),
                ('corrected_category', models.CharField(blank=True, help_text='Si incorrect, spécifier la catégorie réelle (ou laisser vide si aucun objet pertinent).', max_length=100, null=True, verbose_name='catégorie corrigée')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='commentaires')),
            ],
            options={
                'verbose_name': 'Validation Modèle',
                'verbose_name_plural': 'Validations Modèle',
                'ordering': ['-validation_timestamp'],
            },
        ),
    ]
