# Generated by Django 5.2.1 on 2025-05-25 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerouscategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dangerous_categories', to=settings.AUTH_USER_MODEL, verbose_name='créé par'),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='modelvalidation',
            name='detection_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='detection.detectionlog', verbose_name='log de détection'),
        ),
        migrations.AddField(
            model_name='modelvalidation',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to=settings.AUTH_USER_MODEL, verbose_name='validateur'),
        ),
    ]
