# Generated by Django 5.0.4 on 2025-05-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionlog',
            name='contains_dangerous_category',
        ),
        migrations.AddField(
            model_name='dangerouscategory',
            name='category_type',
            field=models.CharField(choices=[('DANGEROUS', 'Dangereuse'), ('HYPERDANGEROUS', 'Hyperdangereuse')], default='DANGEROUS', max_length=20, verbose_name='type de danger'),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='danger_level',
            field=models.CharField(blank=True, choices=[('DANGEROUS', 'Dangereuse'), ('HYPERDANGEROUS', 'Hyperdangereuse')], help_text='Niveau de danger détecté (Dangereuse ou Hyperdangereuse).', max_length=20, null=True, verbose_name='niveau de danger'),
        ),
    ]
