# Generated by Django 5.0.4 on 2025-05-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_remove_detectionlog_contains_dangerous_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlog',
            name='original_file',
            field=models.FileField(blank=True, help_text='Image originale téléversée.', null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='fichier original'),
        ),
    ]
