# Generated by Django 5.2.7 on 2025-10-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_report_detectionlog_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlog',
            name='frames_analyzed',
            field=models.IntegerField(default=0, help_text='Nombre de frames qui ont été analysées dans la vidéo', verbose_name='frames analysés'),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo')], default='IMAGE', help_text='Type de fichier analysé : image ou vidéo', max_length=10, verbose_name='type de média'),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='processing_duration',
            field=models.FloatField(default=0.0, help_text='Temps total de traitement de la détection', verbose_name='durée de traitement (secondes)'),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='video_metadata',
            field=models.JSONField(blank=True, help_text='FPS, durée, résolution, nombre total de frames, etc.', null=True, verbose_name='métadonnées vidéo'),
        ),
    ]
