# Generated by Django 5.2.7 on 2025-11-02 21:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_detectionlog_frames_analyzed_detectionlog_media_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Nom de la catégorie détectée (ex: shotgun, knife)', max_length=100, verbose_name='nom de catégorie')),
                ('validation_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='horodatage validation')),
                ('is_valid', models.BooleanField(help_text='La détection de cette catégorie est-elle correcte ?', verbose_name='catégorie valide?')),
                ('frame_number', models.IntegerField(blank=True, help_text='Frame où cette catégorie a été détectée (pour vidéos)', null=True, verbose_name='numéro de frame')),
                ('confidence', models.FloatField(default=0.0, help_text='Confiance du modèle pour cette détection', verbose_name='confiance')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='commentaires')),
                ('detection_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_validations', to='detection.detectionlog', verbose_name='log de détection')),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_validations', to=settings.AUTH_USER_MODEL, verbose_name='validateur')),
            ],
            options={
                'verbose_name': 'Validation de Catégorie',
                'verbose_name_plural': 'Validations de Catégories',
                'ordering': ['-validation_timestamp'],
                'unique_together': {('detection_log', 'category_name', 'frame_number')},
            },
        ),
    ]
